# Generated by Django 4.2.1 on 2023-06-19 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSidebarBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('event_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Upcoming Events Sidebar Banner',
                'verbose_name_plural': 'Upcoming Events Sidebar Banners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAdLowerBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('ad_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ad_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Ad Middle Banner',
                'verbose_name_plural': 'News Ad Middle Banners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAdLowerLongBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('ad_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ad_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Ad Long Lower Banner',
                'verbose_name_plural': 'News Ad Long Lower Banners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAdSidebarBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('ad_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ad_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Ad Sidebar Banner',
                'verbose_name_plural': 'News Ad Sidebar Banners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify posts by this category', max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NewsNavAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('ad_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ad_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Page Top Advert',
                'verbose_name_plural': 'News Page Top Adverts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(default=datetime.datetime.today)),
                ('twitter', models.CharField(max_length=15)),
                ('instagram', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Social Media Statistic',
                'verbose_name_plural': 'Social Media Statistics',
                'ordering': ['name', 'update_date'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
