# Generated by Django 3.1.2 on 2021-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='type',
            field=models.CharField(choices=[('registration', 'Registration'), ('form', 'Form')], default='full', max_length=255),
        ),
    ]
