# Generated by Django 3.1.2 on 2021-06-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210526_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFormSubmission',
        ),
    ]
