# Generated by Django 3.1.2 on 2021-07-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_delete_customformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='type',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('form', 'Form')], default='full', max_length=255, null=True),
        ),
    ]
