# Generated by Django 3.1.2 on 2021-05-26 16:34

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210526_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='summary',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
