# Generated by Django 3.1.2 on 2021-05-27 01:48

from django.db import migrations, models
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210526_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='overview_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_description',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_title_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_title_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_title_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_title_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='youtube_url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_end_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=27, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_start_day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=27),
        ),
    ]
