# Generated by Django 3.1.2 on 2021-06-01 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210601_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='arrange_event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='arrange_event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
