# Generated by Django 3.1.2 on 2021-07-06 17:12

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210706_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingpage',
            name='paragraph_2',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], null=True),
        ),
    ]
