# Generated by Django 3.1.2 on 2021-09-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20210909_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Partner Event', 'Partner Event'), ('Upcoming Event', 'Upcoming Event')], default='full', max_length=255, null=True),
        ),
    ]
