# Generated by Django 3.1.2 on 2021-12-22 00:24

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20211222_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='description',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], null=True),
        ),
    ]
