# Generated by Django 3.1.2 on 2022-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('news', '0029_auto_20220712_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blockcatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='digitalcatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='exclusivescatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='featurescatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='fintechcatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newscatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='startupscatindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='techcatindexpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_end_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=24, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_end_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=9, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_start_day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=24),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_start_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=9, max_length=20),
        ),
        migrations.DeleteModel(
            name='AICatIndexPage',
        ),
        migrations.DeleteModel(
            name='ArticlesCatIndexPage',
        ),
        migrations.DeleteModel(
            name='BlockCatIndexPage',
        ),
        migrations.DeleteModel(
            name='DigitalCatIndexPage',
        ),
        migrations.DeleteModel(
            name='ExclusivesCatIndexPage',
        ),
        migrations.DeleteModel(
            name='FeaturesCatIndexPage',
        ),
        migrations.DeleteModel(
            name='FintechCatIndexPage',
        ),
        migrations.DeleteModel(
            name='NewsCatIndexPage',
        ),
        migrations.DeleteModel(
            name='StartupsCatIndexPage',
        ),
        migrations.DeleteModel(
            name='TechCatIndexPage',
        ),
    ]
